title: Raul Fragoso
description: Just a place for coding and blogging about my personal projects
google_analytics: 
show_downloads: true
remote_theme: "mmistakes/minimal-mistakes@4.15.2"

gems:
  - jekyll-mentions

plugins:
  - jekyll-include-cache
